### ISSUE TITLE
Next Step Template for Post Purchase

### ISSUE THREAD

**Issue by t6d** [Shopify/shopify-cli-extensions#234]
Since extensions now have the ability to display custom next steps messages, we should take the opportunity to improve the message developers of post purchase messages receive. The message should encourage them to download the Chrome / Firefox extension rather than manually piecing together the checkout URL:

```
If this is the first time you're testing a Post Purchase extension, please install the Chrome or Firefox browser extension from https://github.com/Shopify/post-purchase-devtools/releases. Once installed, simply enter your extension URL https://<tunnel>/extensions/uuid.

If you prefer to test your extension without using our browser extension, create a checkout and append the following query parameter to the checkout URL: ?dev=https://<tunnel>/extensions/uuid
```

**Comment by dmhenry** [comment]
@vividviolet @t6d The last line of this appears to be identical to the "bundle urls", which means I believe I need to iterate over the entry points to get the last component of the URL (`index.[jt]sx?`), which means we could theoretically end up with multiple URL's if there are multiple entrypoints configured. Is that expected/acceptable?

**Comment by vividviolet** [comment]
@dmhenry sorry, I think the last link was incorrect. It should just be the root url. The same root url is used for both the browser extension or the url param
