### ISSUE TITLE
Closing the development server prints a message that looks like an error

### ISSUE THREAD

**Issue by lemonmade** [Shopify/shopify-cli-extensions#294]
Typing control-C to kill the development server prints a red `Interrupt` message, which looks like the CLI's error treatment (even though this is a totally normal operation):

<img width="740" alt="Screen Shot 2022-04-25 at 12 34 22 PM" src="https://user-images.githubusercontent.com/3012583/165174102-2f83ebd9-7961-4f3a-a7b6-626829f6468a.png">

**Comment by jamesvidler** [comment]
Closing this issue as this is no longer the case in CLI 3.
