### ISSUE TITLE
Extension name is not used in any templated files when creating an extension

### ISSUE THREAD

**Issue by lemonmade** [Shopify/shopify-cli-extensions#297]
The name I provide for an extension is used for the directory, but not in a few other places I expected it to be in:

- The `name` field in `package.json` (it uses [`checkout_ui_extension`](https://github.com/Shopify/shopify-cli-extensions/blob/main/create/templates/shared/package.json#L2) no matter what you name the extension)
- The `name` field in `extension.config.yml`, which is empty (I think this name is actually required?)

I was a little confused what I was supposed to put in as name when originally prompted. Are there limits on its length? Where would it be used? Should it be written as prose, or written with a formatting like dash or snake case?

IMO, it would be best to try to show developers we want a sentence-like name, and that that name will be presented to merchants. That lets us use it for the extension.config.yml `name` field, and transform it for use in the directory name and other uses.

**Comment by vividviolet** [comment]
> The name field in package.json (it uses [checkout_ui_extension](https://github.com/Shopify/shopify-cli-extensions/blob/main/create/templates/shared/package.json#L2) no matter what you name the extension)

This is a bug I think

> The name field in extension.config.yml, which is empty (I think this name is actually required?)

This one is supposed to be hardcoded like in the old template: https://github.com/Shopify/checkout-ui-extensions-template/blob/9a505c5410dfa9b1767adce1869e1443ca8f353c/scripts/generate/templates/checkout/files/extension.config.yml#L2. It is also meant to be merchant facing.

> I was a little confused what I was supposed to put in as name when originally prompted. Are there limits on its length? Where would it be used? Should it be written as prose, or written with a formatting like dash or snake case?

The name maps to `title` in the db and is not meant to be surfaced externally. You cannot update them after the fact as far as I know. I think there's limitations but have to dig into the ruby CLI to know what these are. Spaces are converted to underscores so the names are defaulted to snake cases. 

It is very confusing to have 2 configs for "name" and we should align on how to improve this.

**Comment by jamesvidler** [comment]
Cannot reproduce the issue with the name not being set in template files. It looks like this was solved already. Tested this by scaffolding a new app and noted that my app name was set in both the config and the package.json.

**Comment by jamesvidler** [comment]
@lemonmade is this ok to close out?
