### ISSUE TITLE
New extensions do not contain a README

### ISSUE THREAD

**Issue by lemonmade** [Shopify/shopify-cli-extensions#300]
IMO, it is good hygiene to create a basic `README.md` file in a templated project that helps guide the developer on what their new project contains, and what they need to do next.

The new extension CLI does not produce a README at all. The old CLI created one, and though it [wasn’t much, it was something](https://github.com/Shopify/checkout-ui-extensions-template/blob/main/scripts/generate/templates/checkout/files/README.md).

**Comment by dvmrmc** [comment]
@kumar303 I'll be creating some docs over here.

What I found until now is that we host several templates, I'd love to understand if we're willing to cover CLI 2 in addition to CLI3, as they use different sources for the templates.

In the meantime, I'm building a short scaffold of the readme for early feedback too

**Comment by kumar303** [comment]
Hi 👋 

> if we're willing to cover CLI 2 in addition to CLI3

Nope, just CLI 3

> In the meantime, I'm building a short scaffold of the readme for early feedback too

Thanks 🎉
