### ISSUE TITLE
Bug: Post Purchase Index page fails to render

### ISSUE THREAD

**Issue by vividviolet** [Shopify/shopify-cli-extensions#307]
The index page for Post Purchase is now broken:

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/29458473/165541858-4c45704a-eb73-4f56-9b6e-0e8bb395d11e.png">

### Steps to reproduce
1. Install the CLI (12.6.1 is the latest)
2. Run `shopify extension create`
3. Select Post Purchase and then any template
4. Cd into the extension folder and run `shopify extension serve`
5. Click on the link to the extension

**Comment by dmhenry** [comment]
This is no longer broken in the main branch.
