### ISSUE TITLE
Decide on Logging Structure

### ISSUE THREAD

**Issue by dmhenry** [Shopify/shopify-cli-extensions#372]
And logging library?

Relevant elements to log:
- message
- command
- arguments/flags: store, app, template, type, ...
- extension name

**Comment by alfonso-noriega** [comment]
A new [document](https://docs.google.com/document/d/1EaxKuiDOHuukkqayNr_Ot-7JcAwomjhDYnLcwfNuLko/edit#) with a proposal has been open to drive de discussion regarding the logging structure.
