### ISSUE TITLE
Ensure esbuild errors is propagated to build status

### ISSUE THREAD

**Issue by vividviolet** [Shopify/shopify-cli-extensions#72]
Currently when the build fails, the error is shown in the console but it doesn't seem to be propagated upwards to the Develop status.

Steps to reproduce
1. Run `make bootstrap`
2. Run `make run serve < testdata/shopifile.yml`
3. Edit the `tmp/checkout_ui_extension/src/index.tsx` to contain some syntax errors
```tsx
import { render, Text } from "@shopify/checkout-ui-extensions-react";

render("Checkout::Feature::Render", ({ extensionPoint }) => (
  <App extensionPoint={extensionPoint} />
));

function App({ extensionPoint }) {
  return <Text>Welcome to the {extensionPoint} extension!</T>;
}
```
4. See that an error is thrown but no build event is propagated to the notifier
![image](https://user-images.githubusercontent.com/29458473/132061305-92fc4e60-2c14-4043-aa47-3f3e8f2a497c.png)

**Comment by t6d** [comment]
Closed by #115
